# Generated by Django 4.2.1 on 2023-05-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0002_announced_lga_results_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentname",
            name="pollingunit_uniqueid",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="announced_lga_results",
            name="party_score",
            field=models.PositiveIntegerField(),
        ),
    ]
