# Generated by Django 4.2.1 on 2023-05-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0005_announced_state_results_announced_ward_results_lga"),
    ]

    operations = [
        migrations.CreateModel(
            name="party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partyid", models.CharField(max_length=11)),
                ("partyname", models.CharField(max_length=11)),
            ],
        ),
    ]
