# Generated by Django 4.2.1 on 2023-05-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0008_alter_polling_unit_polling_unit_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="states",
            fields=[
                (
                    "state_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("state_name", models.CharField(max_length=50)),
            ],
        ),
    ]
