# Generated by Django 4.2.1 on 2023-05-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0009_states"),
    ]

    operations = [
        migrations.CreateModel(
            name="ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ward_id", models.PositiveIntegerField()),
                ("ward_name", models.CharField(max_length=50)),
                ("lga_id", models.PositiveIntegerField()),
                ("ward_description", models.TextField(max_length=1000)),
                ("entered_by_user", models.CharField(max_length=50)),
                ("date_entered", models.DateTimeField()),
                ("user_ip_address", models.CharField(max_length=50)),
            ],
        ),
    ]
