# Generated by Django 4.2.1 on 2023-05-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0012_remove_lga_date_entered_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="polling_unit",),
    ]
