# Generated by Django 4.2.1 on 2023-05-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0013_delete_polling_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="polling_unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("polling_unit_id", models.PositiveIntegerField()),
                ("ward_id", models.PositiveIntegerField()),
                ("lga_id", models.PositiveIntegerField()),
                ("uniquewardid", models.PositiveIntegerField(null=True)),
                ("polling_unit_number", models.CharField(max_length=50, null=True)),
                ("polling_unit_name", models.CharField(max_length=50, null=True)),
                (
                    "polling_unit_description",
                    models.TextField(max_length=1000, null=True),
                ),
                ("lat", models.CharField(max_length=255, null=True)),
                ("long", models.CharField(max_length=255, null=True)),
                ("entered_by_user", models.CharField(max_length=50, null=True)),
                ("date_entered", models.DateTimeField(auto_now_add=True)),
                ("user_ip_address", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
