# Generated by Django 4.2.1 on 2023-05-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0014_polling_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polling_unit",
            name="date_entered",
            field=models.DateTimeField(),
        ),
    ]
