# Generated by Django 4.2.1 on 2023-05-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0015_alter_polling_unit_date_entered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polling_unit",
            name="date_entered",
            field=models.DateTimeField(null=True),
        ),
    ]
