# Generated by Django 4.2.1 on 2023-05-30 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0016_alter_polling_unit_date_entered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polling_unit",
            name="date_entered",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
