# Generated by Django 4.2.1 on 2023-05-31 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0017_alter_polling_unit_date_entered"),
    ]

    operations = [
        migrations.RemoveField(model_name="polling_unit", name="date_entered",),
    ]
