# Generated by Django 4.2.1 on 2023-05-31 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0020_alter_agentname_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ward",
            name="date_entered",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
